import avatar1 from './avatar1';
import avatar2 from './avatar2';
import avatar3 from './avatar3';
import avatar4 from './avatar4';
import avatar5 from './avatar5';
const users = [
    {   
        id: '1',
        name: 'Анастасия',
        lastName: 'Иванова',
        middleName: 'Сергеевна',
        jobTitle: 'аналитик',
        organization: 'ООО "Иванов"',
        country: 'Россия',
        city: 'Москва',
        email: 'ivanova@demo.com',
        phone: '8-495-123-45-67',
        login: 'ivanova.anastasia',
        admin: true,
        password: 'ivanova',
        birthday: 879410398000,
        skype: 'a.ivanova',
        enrtyDate: 117564480000,
        exitDate: null,
        avatar: avatar1,
    },
    {   
        id: '2',
        birthday: 763160400000,
        email: 'sidorov@demo.com',
        enrtyDate: null,
        entryDate: 1554757200000,
        exitDate: null,
        jobTitle: 'руководитель группы',
        lastName: 'Сидоров',
        login: 'sidorov.semen',
        admin: false,
        middleName: 'Петрович',
        name: 'Семен ',
        organization: 'ООО "Прософт"',
        country: 'Россия',
        city: 'Санкт-Петербург',
        password: 'sidorov',
        phone: '8-499-76-54-321 ',
        skype: ' ',
        avatar: avatar2,
    },
    {   
        id: '3',
        name: 'Иван',
        lastName: 'Смирнов',
        middleName: 'Иванович',
        jobTitle: 'администратор',
        organization: 'Финанс',
        email: 'smirnov@demo.com',
        phone: '8-495-123-45-67',
        login: 'smirnov.ivan',
        admin: true,
        password: 'ivanova',
        birthday: 529576798000,
        skype: 'a.ivanova',
        enrtyDate: 1554757200000,
        exitDate: null,
        avatar: avatar3,
        country: 'Литва',
        city: 'Вильнюс',
    },
    {   
        id: '4',
        name: 'Анна',
        lastName: 'Гордеева',
        middleName: 'Сергеевна',
        jobTitle: 'менеджер',
        organization: 'Финанс',
        email: 'gordeeva@demo.com',
        phone: '8-495-123-45-67',
        login: 'gordeeva.anna',
        admin: true,
        password: 'gordeeva',
        birthday: 529556798000,
        skype: 'a.gordeeva',
        enrtyDate: 1554757200000,
        exitDate: null,
        avatar: avatar4,
        country: 'Литва',
        city: 'Вильнюс',
    },
    {   
        id: '5',
        birthday: 763160400000,
        email: 'durova@demo.com',
        enrtyDate: null,
        entryDate: 1554757200000,
        exitDate: null,
        jobTitle: 'руководитель группы',
        lastName: 'Дурова',
        login: 'durova.valentina',
        admin: true,
        middleName: 'Ивановна',
        name: 'Валентина',
        organization: 'ООО "Прософт"',
        country: 'Россия',
        city: 'Санкт-Петербург',
        password: 'durova',
        phone: '8-499-76-54-321 ',
        skype: ' ',
        avatar: avatar5,
    },
];

export default users;
